apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: etl-sim
  namespace: monitoring
  labels:
    app: etl-sim
spec:
  namespaceSelector:
    matchNames: ["kubehealer"]
  selector:
    matchLabels:
      app: etl-sim
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 3s