auth:
  rootUser: minio
  rootPassword: minio123
defaultBuckets: etl-bucket,training-data,replay-buffer

service:
  ports:
    api: 9002

consoleService:
  enabled: true
  ports:
    console: 9011   # <-- desired Service port

persistence:
  enabled: true
  size: 10Gi
  storageClass: local-path
